version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    tty: true
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: .docker/app
      dockerfile: Dockerfile
    environment:
      LANG: 'ja_JP.UTF-8'
      TZ: 'Asia/Tokyo'
      APP_NAME: 'PHP'
      APP_ENV: 'development'
      APP_DEBUG: 'true'
      APP_URL: 'http://localhost'
      LOG_CHANNEL: 'stderr'
      DB_CONNECTION: 'pgsql'
      DB_HOST: 'docker_hazard_map_db'
      DB_PORT: '5432'
      DB_DATABASE: 'hazard_db'
      DB_DATABASE_TEST: 'cake_testing'
      DB_USERNAME: 'user'
      DB_PASSWORD: '16210a0c-d1cd-fd9e-7746-b042e3bfa723'
    # env_file:
    #   - .env
    volumes:
      - .:/var/www/html
    expose:
      - 9000
    tty: true
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: docker_hazard_map_db
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_USER: 'user'
      POSTGRES_ROOT_PASSWORD: '3030ebaf-111f-5958-eada-c3b856714a09'
      POSTGRES_PASSWORD: '16210a0c-d1cd-fd9e-7746-b042e3bfa723'
      POSTGRES_DB: 'hazard_db'
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/data
      - ./.docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432